language: lisp
sudo: required

env:
  matrix:
    - LISP=sbcl

addons:
  apt:
    packages:
      - sbcl
      - python3-pip
      - python3-numpy

install:
  - sbcl --version
  - git clone --branch v2.3.0 https://github.com/digikar99/py4cl2.git
  - git clone -b release https://github.com/roswell/roswell.git
  - cd roswell 
  - sh bootstrap
  - ./configure
  - make && sudo make install
  - ros install sbcl-bin
  - cd ~/
  - ls

script:
  - ros -e '(push (uiop:getcwd) ql:*local-project-directories*)
            (ql:quickload :numericals)
            (ql:quickload :numericals/tests)
            (setq 5am:*on-error* nil)
            (setq 5am:*on-failure* nil)' run -- --dynamic-space-size 2048 --eval '(uiop:quit (if (numericals/tests:run-correctness-tests) 0 1))'
    [ $? -eq 1 ]

notifications:
  email: false