site_name: (dense-)numericals
theme:
    name: readthedocs
    collapse_by_default: false
    highlightjs: true
    hljs_languages:
        - lisp
    navigation_depth: 4
    sticky_navigation: false
    prev_next_buttons_location: none
include_search_page: true
nav:
    - Introduction: index.md
    - Writing Fast Code Fast: common-lisp-and-numericals.md
    - Installation: install.md
    - Current State: comparison.md
    - Manual: manual.md
    - Old Documentation: old-index.html
plugins:
    - search
extra_css: [extra.css]
